version: "2"

services:
  jmaster:
    build: master/
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - $HOME/.ssh:/var/jenkins_home/.ssh
      - $HOME/jenkins-backup/jobs:/var/jenkins_home/jobs

  jslave:
    build: slave/

  registry:
    image: registry:2.4.0
    volumes:
      - $HOME/jenkins-backup/registry:/var/lib/registry