version: "2"

services:
  jmaster:
    image: localhost:5000/reference/jmaster:${VERSION}
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ${SSH_VOLUME}
      - ${BACKUP_VOLUME}

  jslave:
    image: localhost:5000/reference/jslave:${VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
      - ${GRADLE_VOLUME}

  registry:
    image: registry:2.4.0
    ports:
      - 5000:5000
    volumes:
      - $HOME/jenkins-backup/registry:/var/lib/registry

  registry-web:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8081:80
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
      - ENV_MODE_BROWSE_ONLY=true
